version: '3.8'
services:
  elasticsearch:
    build:
      context: .
      args:
        ELK_VERSION: 7.17.4
    container_name: elasticsearch
    environment:
      - node.name=single-node
      - cluster.name=eureka
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic-bridge
  kibana:
    container_name: Kibana
    image: docker.elastic.co/kibana/kibana:7.17.4
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic-bridge

networks:
  elastic-bridge:
    driver: bridge
